"""add deactivated_at to accounts

Revision ID: 39042df55485
Revises: e7c4852c216e
Create Date: 2026-09-28 18:22:55.725408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39042df55485'
down_revision: Union[str, Sequence[str], None] = 'e7c4852c216e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Backfill: any account that's already inactive needs a deactivated_at or
    # account_balance_as_of would fall back to its last snapshot date (the
    # pre-migration behavior) instead of treating it as "just deactivated".
    # updated_at is the closest thing we have to when that happened, since
    # deactivating an account always touches updated_at.
    op.execute(
        "UPDATE accounts SET deactivated_at = updated_at WHERE is_active = 0"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'deactivated_at')
    # ### end Alembic commands ###
